### ISSUE TITLE
App-test.js failed

### ISSUE THREAD

**Issue by coverney** [santosfamilyfoundation/RuinaMain#53]
The only test from last year was `App-test.js` which tries to render the app correctly, but when I tried to run it, it failed with the following error (the file is located in the `__tests__` folder):
```
TypeError: Cannot read property 'Direction' of undefined

      at Object.<anonymous> (node_modules/react-native-gesture-handler/Directions.js:3:39)
      at Object.<anonymous> (node_modules/react-native-gesture-handler/GestureHandler.js:2:1)
```

**Comment by coverney** [comment]
I got it to work! Will push fix!
